### ISSUE TITLE
[1.14.4] Blocks lack hardness

### ISSUE THREAD

**Issue by ProsperCraft** [SkyNetCloud/SuperCyber#3]
All of the blocks lack hardness and can be mined with anything even a book.

**Comment by SkyNetCloud** [comment]
Thank you for pointing this out I will fix this right away what version of Minecraft are you on?

**Comment by ProsperCraft** [comment]
See the topic, 1.14.4

**Comment by ProsperCraft** [comment]
Also the blocks lacking hardness also have a shoveling dirt sound when harvested.

**Comment by SkyNetCloud** [comment]
Fixed In version 1.3 So now closing this
