### ISSUE TITLE
[1.14.4] The nbt data on the mods items say Cx would be more helpful if they said SuperCyber

### ISSUE THREAD

**Issue by ProsperCraft** [SkyNetCloud/SuperCyber#4]
The nbt data on the mods items say Cx would be more helpful if they said SuperCyber

![2019-07-25_20 02 52](https://user-images.githubusercontent.com/4427684/61926076-5de19f00-af2c-11e9-859a-321570126b85.png)

**Comment by SkyNetCloud** [comment]
I will fix that right away be tho aware that items and blocks might not be there when you update to the next versions of the mod as I have to update the mod Id

**Comment by SkyNetCloud** [comment]
Fixed In version 1.3
